name: "Minecraft 崩溃"
description: "Minecraft 客户端意外退出"
labels: "等待确认"

title: "[Crash] "

body:
- type: checkboxes
  id: checklist
  attributes:
    label: 检查单
    description: "请逐项确认以下内容："
    options:
      - label: "我在其他启动器上未成功复现此问题，只有 PCL.Mac 启动器有这个问题。"
        required: true
      - label: "我已将启动器更新至最新版，并且该问题依然存在。"
        required: true
      - label: "我确认此问题没有被其他人报告过。"
        required: true
- type: textarea
  id: steps
  attributes:
    label: 复现方式
    placeholder: |
      1. xxx
      2. xxx
  validations:
    required: true
  id: log
  attributes:
    label: 错误报告
    placeholder: "请在崩溃页面点击“导出错误报告”，并将错误报告上传。"
  validations:
    required: true
