name: Build macOS App

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App 版本'
        required: true
        default: '0.0.0'

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate Environment.xcconfig
        run: |
            echo "IS_DEVELOPMENT = false" >> Environment.xcconfig
            echo "BRANCH = $BRANCH" >> Environment.xcconfig
            echo "APP_VERSION = $APP_VERSION" >> Environment.xcconfig
        env:
          BRANCH: ${{ github.ref_name }}
          APP_VERSION: ${{ github.event.inputs.app_version }}
    
      - name: Replace secrets
        run: |
            sed -i '' "s/{{ARTIFACT_PAT}}/$ARTIFACT_PAT/g" PCL.Mac/Secrets.swift
            sed -i '' "s/{{CLIENT_ID}}/$CLIENT_ID/g" PCL.Mac/Secrets.swift
            sed -i '' "s/{{THEME_KEY}}/$THEME_KEY/g" PCL.Mac/Secrets.swift
        env:
          ARTIFACT_PAT: ${{ secrets.ARTIFACT_PAT }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          THEME_KEY: ${{ secrets.THEME_KEY }}

      - name: Build Universal Binary (xcodebuild)
        run: |
          PROJECT="PCL.Mac.xcodeproj"
          SCHEME="PCL.Mac"

          if [ -d "$PROJECT" ]; then
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Release -archivePath build \
              -xcconfig Environment.xcconfig \
              ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO archive
          else
            echo "PCL.Mac.xcodeproj not found!"
            exit 1
          fi

      - name: Archive build products
        uses: actions/upload-artifact@v4
        with:
          name: PCL.Mac
          path: build.xcarchive/Products/Applications/PCL.Mac.app
