name: Build PCL-Mac (Universal)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-universal:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
    
    - name: Build Universal Binary
      run: |
        xcodebuild -scheme "PCL-Mac" \
                   -configuration Release \
                   -destination "platform=macOS" \
                   ARCHS="arm64 x86_64" \
                   ONLY_ACTIVE_ARCH=NO \
                   clean build
        
        mkdir -p build/universal
        PRODUCTS_DIR=$(xcodebuild -scheme "PCL-Mac" -configuration Release -showBuildSettings | grep "BUILT_PRODUCTS_DIR" | grep -oEi "/.*")
        cp -R "$PRODUCTS_DIR" build/universal
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PCL-Mac-Universal
        path: build/universal
